CREATE DATABASE IF NOT EXISTS BANCO;

USE BANCO;

CREATE TABLE IF NOT EXISTS GERENTE(
codigo INT AUTO_INCREMENT NOT NULL, 
nombre VARCHAR(75) NOT NULL,
turno VARCHAR(25) NOT NULL,
dpi VARCHAR(40) NOT NULL,
direccion VARCHAR(150) NOT NULL,
sexo VARCHAR(50) NOT NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY(codigo)
);

INSERT INTO GERENTE VALUES(0,'JUAN PACO PEDRO DE LA MAR','MATUTINO','1234567891011','MALACATÁN, SAN MARCOS.','M');

CREATE TABLE IF NOT EXISTS CAJERO(
codigo INT AUTO_INCREMENT NOT NULL, 
nombre VARCHAR(75) NOT NULL,
turno VARCHAR(25) NOT NULL,
dpi VARCHAR(40) NOT NULL,
direccion VARCHAR(150) NOT NULL,
sexo VARCHAR(50) NOT NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY(codigo)
);

INSERT INTO CAJERO VALUES(177840,'Mario Diaz','MATUTINO','89505278065','MALACATÁN, SAN MARCOS','M');
INSERT INTO CAJERO VALUES(118258,'Lucia Coti','VESPERTINO','1248895321','MALACATÁN, SAN MARCOS','F');

CREATE TABLE IF NOT EXISTS CLIENTE(
codigo INT AUTO_INCREMENT NOT NULL, 
nombre VARCHAR(75) NOT NULL,
dpi VARCHAR(40) NOT NULL,
nacimiento DATE NOT NULL,
direccion VARCHAR(150) NOT NULL,
sexo VARCHAR(50) NOT NULL,
pdf LONGBLOB NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY(codigo)
);

CREATE TABLE IF NOT EXISTS USUARIO(
user INT AUTO_INCREMENT NOT NULL,
registro INT NOT NULL,
roll VARCHAR(75) NOT NULL,
pass VARCHAR(75) NOT NULL,
pdf LONGBLOB NULL,
CONSTRAINT PK_USER PRIMARY KEY(user)
);

ALTER TABLE USUARIO AUTO_INCREMENT=77;
INSERT INTO USUARIO (user,registro,roll,pass) VALUES(0,1,'GERENTE','ASDF1234');
INSERT INTO USUARIO (user,registro,roll,pass) VALUES(0,177840,'CAJERO','puto123');
INSERT INTO USUARIO (user,registro,roll,pass) VALUES(0,118258,'CAJERO','princess');

CREATE TABLE IF NOT EXISTS CUENTA(
codigo INT AUTO_INCREMENT NOT NULL,
cliente INT NOT NULL,
creacion DATE NOT NULL,
saldo DECIMAL(65,2) NOT NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY(codigo),
CONSTRAINT FK_CLIENTE FOREIGN KEY(cliente)
REFERENCES CLIENTE(codigo)
);

CREATE TABLE IF NOT EXISTS TRANSACCION(
codigo INT AUTO_INCREMENT NOT NULL,
cuenta INT NOT NULL,
fecha DATE NOT NULL,
hora TIME NOT NULL,
tipo VARCHAR(30) NOT NULL,
monto DECIMAL(65,2) NOT NULL,
cajero INT NOT NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY(codigo),
CONSTRAINT FK_CUENTA FOREIGN KEY(cuenta)
REFERENCES CUENTA(codigo),
CONSTRAINT FK_CAJERO FOREIGN KEY(cajero)
REFERENCES CAJERO(codigo)
);

CREATE TABLE IF NOT EXISTS ASOCIACION(
codigo INT AUTO_INCREMENT NOT NULL,
ccuenta INT NOT NULL,
ccliente INT NOT NULL,
estado VARCHAR(75) NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY(codigo),
CONSTRAINT FK_CCUENTA FOREIGN KEY(ccuenta)
REFERENCES CUENTA(codigo),
CONSTRAINT FK_CCLIENTE FOREIGN KEY(ccliente)
REFERENCES CLIENTE(codigo)
);

CREATE TABLE IF NOT EXISTS LIMITES(
codigo INT AUTO_INCREMENT NOT NULL,
gerente INT NOT NULL,
limite_1 INT NOT NULL,
limite_2 INT NOT NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY(codigo),
CONSTRAINT FK_GERENTE FOREIGN KEY(gerente)
REFERENCES GERENTE(codigo)
);

CREATE TABLE IF NOT EXISTS HISTORIAL(
registro INT AUTO_INCREMENT NOT NULL,
cgerente INT NOT NULL,
cusuario INT NOT NULL,
nombre VARCHAR(75) NOT NULL,
turno VARCHAR(25) NULL,
nacimiento DATE NULL,
dpi VARCHAR(40) NOT NULL,
direccion VARCHAR(150) NOT NULL,
sexo VARCHAR(50) NOT NULL,
fecha DATE NOT NULL,
CONSTRAINT PK_REGISTRO PRIMARY KEY(registro),
CONSTRAINT FK_CGERENTE FOREIGN KEY(cgerente)
REFERENCES GERENTE(codigo),
CONSTRAINT FK_CUSUARIO FOREIGN KEY(cusuario)
REFERENCES USUARIO(user)
);
